server:
  port: 9090
  tomcat.uri-encoding: UTF-8

img:
  location: D:/java/xyf/img/
  locations: D:/java/xyf/page/

spring:
  resources:
    #图片访问路径
    static-locations: file:${img.location},file:${img.locations}
  mvc:
    static-path-pattern: /**
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://122.114.254.63:3306/wei?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: admin
      password: xyf123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #日期格式，东八区
  jackson:
    data-format : yyyy-MM-dd
    timezone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xyf.model


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
  level:
    com.xyf.dao: debug
  file: /log/my.log


management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
    path: /xyf



